services:
  app:
    build: .
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["/app/video-conference" ]
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - messenger

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: videoconference
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - messenger

networks:
  messenger:
    external: true

volumes:
  pgdata: